### ISSUE TITLE
Setting smartmap field to required does nothing

### ISSUE THREAD

**Issue by piotrpog** [doublesecretagency/craft-smartmap#14]
I think setting this option for field should make longitude and latitude sub-fields required.

**Comment by lindseydiloreto** [comment]
This is a known issue, which has existed for a long time.

The problem is, "required" means different things for different people. Some folks (like you) only care about making the coordinates required. Others want the entire address to be filled out. And yet others only care about subfields that are critical _to them_, like the State or Zip.

I do plan on addressing this in a future version. Thanks for posting it!

**Comment by lindseydiloreto** [comment]
This issue has been migrated to the Google Maps repo. To stay up-to-date, subscribe over there...

- https://github.com/doublesecretagency/craft-googlemaps/issues/3
