### ISSUE TITLE
Region biasing with coordinates for target returns bad result

### ISSUE THREAD

**Issue by missmatsuko** [doublesecretagency/craft-smartmap#39]
Example query in Twig:
```
{% set stores = craft.entries
  .section('store')
  .location({
    target: target,
    components: {
      administrative_area: 'AB',
      country: 'CA',
    },
  })
  .orderBy('distance')
  .all()
%}
```

When target is a coordinates, like `'53.5444, -113.4909'` (meant to be middle of Edmonton, AB, CA), it returns one entry which is not located in Edmonton, AB. 

When I remove 'components', I get 79 results. The first bunch are in Edmonton, and the last I assume are probably near Edmonton (this is the expected/good result).

If I keep the 'components' parameter and use the string `'Edmonton'` rather than coordinates, I also get 79 results and they're mostly in Edmonton, too.

The one result I got when I had coordinates and region biasing is not in the 79 results.

**Comment by lindseydiloreto** [comment]
Huh, interesting. That's definitely weird behavior.

I'll dig a little deeper into it, not sure what could be causing that. For the moment, I'm just going to blame Google. 🙂

**Comment by lindseydiloreto** [comment]
I'm thinking about this a little more... if you're specifying coordinates as the `target`, then the region biasing is extraneous and unnecessary. You can (and probably should) safely omit the `components` when the `target` is a set of coordinates.

Ultimately, I do agree that they shouldn't be causing a conflict (which is what appears to be happening). It's likely that the underlying code is branching in a weird way, and preventing both directives from accomplishing their goal.

As a relatively safe workaround, I'd recommend just running a check on the string before passing it in as the `target`. If the string is determined to be a set of coordinates, omit `components` from the search parameters.

Hope that helps!

**Comment by missmatsuko** [comment]
Yeah, I was hoping that check could be done on the plugin's side so I wouldn't have to do it in Twig or make a module.

**Comment by lindseydiloreto** [comment]
Possibly. I'd love to refactor the underlying code in that neighborhood, so I'll keep that in mind. 👍

**Comment by lindseydiloreto** [comment]
We just released the new Google Maps plugin this week, and the [proximity search](https://plugins.doublesecretagency.com/google-maps/proximity-search/) functionality is much more flexible that it was previously. It's obviously been awhile since you dealt with this issue, but I'm about 90% confident that it would be smoother and easier to deal with in the new plugin.

Here's a rundown of the modernized [`target`](https://plugins.doublesecretagency.com/google-maps/proximity-search/options/#target) option...

<img width="777" alt="target" src="https://user-images.githubusercontent.com/5309692/109404005-ab976800-7916-11eb-9f54-f973ccd1d2c4.png">
