### ISSUE TITLE
API Issue

### ISSUE THREAD

**Issue by Takaya213** [doublesecretagency/craft-smartmap#44]
The API for Google Maps has been setup as per the instructions in the documentation, but whenever we input an address and say Search Address we get the following error:

This API project is not authorized to use this API.

We are using the trial version with the intention to purchase the plugin.

**Comment by lindseydiloreto** [comment]
Hi there. This is definitely an issue with the configuration of your Google API keys. It sounds like they currently do not allow for the API keys to be used in that particular environment.

The Google interface is very confusing, I know... but I assure you the solution is due to how the API keys are configured.

**Comment by Takaya213** [comment]
Hi @lindseydiloreto. Thanks I will take a look, and agreed the Google interface is confusing, as well as it has been updated since the docs about how to get the API keys was done, so the screenshots are all rather out of date as well as the instructions.

**Comment by lindseydiloreto** [comment]
Too true, sadly... it seems that Google likes to reinvent their documentation every 6-12 months. I've updated that page of the Smart Map docs several times to keep up, but it's been a significant moving target.

I may actually _trim back_ that page of the docs in the future, and simply bullet-list the API key requirements. It's not worth the effort of continually making new screenshots if they're just going to be outdated within a year.
