### ISSUE TITLE
Undefined class constant 'EVENT_REGISTER_EXPORTERS'

### ISSUE THREAD

**Issue by darylknight** [doublesecretagency/craft-smartmap#55]
I just updated Smart Map to 3.3.0 locally and I can't access the control panel because I'm seeing Error: Undefined class constant 'EVENT_REGISTER_EXPORTERS'.

![image](https://user-images.githubusercontent.com/1250017/81169390-7691e180-8fa1-11ea-9811-0a3a9f404cf9.png)

I do actually have it running perfectly fine on another site locally, so I wonder if this is specifically related to a migration or updating?

PHP 7.4.3
Craft 3.4.18
Smart Map 3.3.0

**Comment by darylknight** [comment]
I updated Smart Map at the same time as updating Craft from 3.3.20.1 to 3.4.18 - it looks like that's what caused it. Updating Craft first _then_ Smart Map has fixed the issue.

**Comment by lindseydiloreto** [comment]
Interesting... Even though the "Export" button was introduced in Craft 3.2, it looks like the `EVENT_REGISTER_EXPORTERS` event wasn't introduced until 3.4.

I've just bumped the minimum requirement. Good catch, thanks!

**Comment by lindseydiloreto** [comment]
Since it looks like I may end up linking back to this thread for other folks dealing with the same issue, figured I'd add a little extra information...

This is the result of a brief misunderstanding I had regarding the introduction of Craft's native  "Export" feature. They introduced the _concept_ of exporting in 3.2, but didn't introduce the _event_ until 3.4. As a result of the confusion, Smart Map was briefly allowed to be installed on a Craft version which was _too old_ (anywhere between Craft 3.2 - 3.4).

Patching this issue led to a small (but notable) composer-based tangle. You can't see the fix until you update Craft first. It's Composer's fault, there is no way around it.

**The solution is to update to Craft 3.4 first**, then update Smart Map second. A newer version of Smart Map ([v3.3.1](https://github.com/doublesecretagency/craft-smartmap/blob/v3/CHANGELOG.md#331---2020-05-06)) will become available to you once you have updated Craft.
