### ISSUE TITLE
Feed me support

### ISSUE THREAD

**Issue by keithmancuso** [doublesecretagency/craft-smartmap#6]
Curious if you had any plans to add support for feed me?  As far as i can tell seems like you can add support for it similar to how you did for craftql?

Would be a huge help for a project im working on that involves syncing data from yelp weekly with feedme!

**Comment by lindseydiloreto** [comment]
Yup, I absolutely intend to (re)introduce support for Feed Me! I wasn't able to get it into the initial 3.0 release, because Feed Me for Craft 3 hadn't been released yet.

My plan was to do it this week, but I'm getting on a plane for Peers tomorrow. So realistically, I'll be tackling it next week when I get back.

**Comment by engram-design** [comment]
@keithmancuso We'll be implementing third-party support natively, we'll keep you posted.

**Comment by lindseydiloreto** [comment]
Brilliant, thanks @engram-design!

**Comment by lindseydiloreto** [comment]
Support for Smart Map was added to Feed Me in [v3.0.0-beta.12](https://github.com/verbb/feed-me/releases/tag/3.0.0-beta.12)
