### ISSUE TITLE
Pin Clustering

### ISSUE THREAD

**Issue by CreateSean** [doublesecretagency/craft-smartmap#67]
Craft 3.5.17.1
Smart Map 3.3.5

I would like to be able to cluster pins so that if there are say 10 pins close together it would show a single pin with a number 10 until you zoom in.  

Have tried to search docs for cluster. however it appears your search bar on the docs isn't hooked up.

For example in this screenshot this would be very helpful.
![image](https://user-images.githubusercontent.com/6899490/103546771-871c9380-4e71-11eb-9b27-f7730dd991c1.png)

**Comment by lindseydiloreto** [comment]
Great note! I could've sworn this issue was already on Github, but perhaps I'm just thinking of [this SE post...](https://craftcms.stackexchange.com/a/28730/45)

I do plan on making clustering a native feature. It relies on a separate JS library though, so it's just a tiny bit complicated to integrate. In the meantime, check out that SE post for details on how to implement it yourself.

I definitely do want to make marker clustering a lot easier and more native! I'll keep this thread open as a feature request until I eventually get to it. 👍

**Comment by CreateSean** [comment]
@lindseydiloreto Thanks - perhaps you could update the documentation so that it's easy to find out about the extra steps.

**Comment by lindseydiloreto** [comment]
This issue has been migrated to the Google Maps repo. To stay up-to-date, subscribe over there...

 - https://github.com/doublesecretagency/craft-googlemaps/issues/9
