### ISSUE TITLE
Options: static Map height not accurately responding 

### ISSUE THREAD

**Issue by stovepot** [doublesecretagency/craft-smartmap#7]
The options: `height` variable varies on a static map. `{{ craft.smartMap.img(locations, options) }}`

eg: 100 = 160px, 350 = 487px.

All css/js checked however no overrides found. 

Running:

PHP version | 7.1.0
-- | --
MySQL 5.6.38
Imagick 3.4.3RC1 (ImageMagick 6.9.6-2)
Craft Solo 3.0.3.1

**Comment by lindseydiloreto** [comment]
I know this is a very, very old ticket, sorry for never responding. Are you still seeing issues with this?

The only thing I can think of that may be causing this behavior is the retina output. Whatever number you specify (ie: 100) is automatically doubled (ie: 200), which is then rendered in an `<img>` tag which (theoretically) has a `height="100"` attribute. Perhaps there is a reason why your browser is squishing it differently, giving you a number between 100 - 200 (ie: 160).

<img width="651" alt="Ω 2020-03-01 at 9 06 23 PM" src="https://user-images.githubusercontent.com/5309692/75647063-9521d800-5c00-11ea-892f-0545a9d65bd6.png">

https://www.doublesecretagency.com/plugins/smart-map/docs/customizing-the-map-in-twig

Let me know if you're still having any issues related to this ticket. I'm going to close this thread because it is so damn old, but I'm happy to re-open it if you're still experiencing problems.
